create extension if not exists pg_trgm;

create table sys_department
(
    id          int8 generated by default as identity,
    parent_id   int8,
    sort        int4,
    description text,
    name        text,
    primary key (id)
);

create table sys_permission
(
    id          int8 generated by default as identity,
    parent_id   int8,
    sort        int4,
    code        text,
    description text,
    name        text,
    primary key (id)
);

create table sys_role
(
    id          int8 generated by default as identity,
    code        text,
    description text,
    name        text,
    primary key (id)
);

create table sys_role_permission
(
    sys_role_id       int8 not null,
    sys_permission_id int8 not null,
    primary key (sys_role_id, sys_permission_id)
);

create table sys_user
(
    id            int8 generated by default as identity,
    email         text,
    password      text,
    username      text,
    department_id int8,
    primary key (id)
);

create table sys_user_role
(
    sys_user_id int8 not null,
    sys_role_id int8 not null,
    primary key (sys_user_id, sys_role_id)
);

alter table if exists sys_department
    add constraint uc_sys_department_name unique (name);
CREATE INDEX idx_sys_department_name ON sys_department using gin (name gin_trgm_ops);

alter table if exists sys_permission
    add constraint uc_sys_permission_name_code unique (name, code);
CREATE INDEX idx_sys_permission_name ON sys_permission using gin (name gin_trgm_ops, code gin_trgm_ops);

alter table if exists sys_role
    add constraint uc_sys_role_name_code unique (name, code);
CREATE INDEX idx_sys_role_name ON sys_role using gin (name gin_trgm_ops, code gin_trgm_ops);

alter table if exists sys_role_permission
    add constraint FKmnbc71b4040rgprkv4aeu0h5p
        foreign key (sys_permission_id)
            references sys_permission;

alter table if exists sys_role_permission
    add constraint FK31whauev046d3rg8ecubxa664
        foreign key (sys_role_id)
            references sys_role;

alter table if exists sys_user
    add constraint FKgpcudn9q6i2xhnbngujxwgqij
        foreign key (department_id)
            references sys_department;

alter table if exists sys_user_role
    add constraint FK1ef5794xnbirtsnudta6p32on
        foreign key (sys_role_id)
            references sys_role;

alter table if exists sys_user_role
    add constraint FKsbjvgfdwwy5rfbiag1bwh9x2b
        foreign key (sys_user_id)
            references sys_user;

INSERT INTO sys_department (parent_id, sort, description, name)
VALUES (null, 0, '官网: https://zhengchalei.github.io', '总部');
INSERT INTO sys_department (parent_id, sort, description, name)
VALUES (1, 0, null, '上海分公司');
INSERT INTO sys_department (parent_id, sort, description, name)
VALUES (2, 0, null, '上海分公司开发部');

INSERT INTO sys_user(email, password, username, department_id)
VALUES ('stone981023@gmail', '123456', 'admin', 1);
